# Generated by Django 4.2.6 on 2024-03-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auctionitem_winner_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
