# Generated by Django 4.2.6 on 2024-03-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auctionitem_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
