# Generated by Django 4.2.2 on 2024-04-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_refundrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='sketchfab_script',
            field=models.TextField(blank=True, null=True),
        ),
    ]
